"""Add dosya_limiti

Revision ID: 58a58a9a5859
Revises: f8c3d2e1a9b0
Create Date: 2026-04-22 16:10:59.898669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a58a9a5859'
down_revision: Union[str, Sequence[str], None] = 'f8c3d2e1a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vektor_parcalari_arama_vektoru'), postgresql_using='gin')
        batch_op.drop_column('arama_vektoru')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arama_vektoru', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_vektor_parcalari_arama_vektoru'), ['arama_vektoru'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
