"""turkce_tam_sema

Revision ID: cd62cda0a732
Revises: 5092dce06153
Create Date: 2026-03-22 23:28:34.795884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cd62cda0a732'
down_revision: Union[str, Sequence[str], None] = '5092dce06153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_modelleri',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('ad', sa.String(length=128), nullable=False),
    sa.Column('tedarikci', sa.String(length=64), nullable=True),
    sa.Column('api_anahtari', sa.String(length=1024), nullable=False),
    sa.Column('model_id', sa.String(length=256), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('yapilandirma', sa.JSON(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('kimlik'),
    sa.UniqueConstraint('ad', name='uq_ai_modelleri_ad')
    )
    with op.batch_alter_table('ai_modelleri', schema=None) as batch_op:
        batch_op.create_index('ix_ai_modelleri_tedarikci', ['tedarikci'], unique=False)

    op.create_table('kullanicilar',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('eposta', sa.String(length=255), nullable=False),
    sa.Column('tam_ad', sa.String(length=128), nullable=False),
    sa.Column('sifre_karma', sa.String(length=128), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('super_kullanici_mi', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.Column('son_giris_tarihi', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('kimlik'),
    sa.UniqueConstraint('eposta')
    )
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.create_index('ix_kullanicilar_eposta', ['eposta'], unique=False)

    op.create_table('roller',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('ad', sa.String(length=64), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('izinler', sa.JSON(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('kimlik'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('sistem_ayarlari',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('anahtar', sa.String(length=128), nullable=False),
    sa.Column('deger', sa.JSON(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('hassas_mi', sa.Boolean(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.Column('guncelleme_tarihi', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('kimlik'),
    sa.UniqueConstraint('anahtar')
    )
    with op.batch_alter_table('sistem_ayarlari', schema=None) as batch_op:
        batch_op.create_index('ix_sistem_ayarlari_anahtar', ['anahtar'], unique=False)

    op.create_table('belgeler',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('yukleyen_kimlik', sa.String(length=36), nullable=True),
    sa.Column('dosya_adi', sa.String(length=512), nullable=False),
    sa.Column('dosya_turu', sa.String(length=32), nullable=False),
    sa.Column('dosya_boyutu_bayt', sa.Integer(), nullable=True),
    sa.Column('depolama_yolu', sa.String(length=1024), nullable=True),
    sa.Column('vektordb_koleksiyon', sa.String(length=128), nullable=True),
    sa.Column('parca_sayisi', sa.Integer(), nullable=False),
    sa.Column('erisim_politikasi', sa.String(length=64), nullable=False),
    sa.Column('durum', sa.String(length=32), nullable=False),
    sa.Column('vektorlestirildi_mi', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.Column('guncelleme_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['yukleyen_kimlik'], ['kullanicilar.kimlik'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('belgeler', schema=None) as batch_op:
        batch_op.create_index('ix_belgeler_dosya_turu', ['dosya_turu'], unique=False)
        batch_op.create_index('ix_belgeler_durum', ['durum'], unique=False)
        batch_op.create_index('ix_belgeler_erisim_politikasi', ['erisim_politikasi'], unique=False)
        batch_op.create_index('ix_belgeler_vektordb_koleksiyon', ['vektordb_koleksiyon'], unique=False)
        batch_op.create_index('ix_belgeler_yukleyen_kimlik', ['yukleyen_kimlik'], unique=False)

    op.create_table('bilgisayar_oturumlari',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('kullanici_kimlik', sa.String(length=36), nullable=True),
    sa.Column('ip_adresi', sa.String(length=64), nullable=True),
    sa.Column('mac_adresi', sa.String(length=32), nullable=True),
    sa.Column('bilgisayar_adi', sa.String(length=255), nullable=True),
    sa.Column('isletim_sistemi', sa.String(length=128), nullable=True),
    sa.Column('tarayici', sa.String(length=256), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('ilk_baglanti_tarihi', sa.String(length=32), nullable=False),
    sa.Column('son_aktivite_tarihi', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_kimlik'], ['kullanicilar.kimlik'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('bilgisayar_oturumlari', schema=None) as batch_op:
        batch_op.create_index('ix_bilgisayar_oturumlari_ip_adresi', ['ip_adresi'], unique=False)
        batch_op.create_index('ix_bilgisayar_oturumlari_mac_adresi', ['mac_adresi'], unique=False)
        batch_op.create_index('ix_bilgisayar_oturumlari_son_aktivite', ['son_aktivite_tarihi'], unique=False)

    op.create_table('denetim_izleri',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('kullanici_kimlik', sa.String(length=36), nullable=True),
    sa.Column('islem_turu', sa.String(length=32), nullable=False),
    sa.Column('tablo_adi', sa.String(length=128), nullable=True),
    sa.Column('kayit_kimlik', sa.String(length=36), nullable=True),
    sa.Column('eski_deger', sa.JSON(), nullable=True),
    sa.Column('yeni_deger', sa.JSON(), nullable=True),
    sa.Column('ip_adresi', sa.String(length=64), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_kimlik'], ['kullanicilar.kimlik'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('denetim_izleri', schema=None) as batch_op:
        batch_op.create_index('ix_denetim_izleri_islem_turu', ['islem_turu'], unique=False)
        batch_op.create_index('ix_denetim_izleri_kullanici_kimlik', ['kullanici_kimlik'], unique=False)
        batch_op.create_index('ix_denetim_izleri_olusturulma_tarihi', ['olusturulma_tarihi'], unique=False)
        batch_op.create_index('ix_denetim_izleri_tablo_adi', ['tablo_adi'], unique=False)

    op.create_table('kullanici_roller',
    sa.Column('kullanici_kimlik', sa.String(length=36), nullable=False),
    sa.Column('rol_kimlik', sa.String(length=36), nullable=False),
    sa.Column('atanma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_kimlik'], ['kullanicilar.kimlik'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_kimlik'], ['roller.kimlik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kullanici_kimlik', 'rol_kimlik')
    )
    op.create_table('sohbet_oturumlari',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('kullanici_kimlik', sa.String(length=36), nullable=True),
    sa.Column('baslik', sa.String(length=256), nullable=True),
    sa.Column('kullanilan_model', sa.String(length=128), nullable=True),
    sa.Column('koleksiyon_adi', sa.String(length=128), nullable=True),
    sa.Column('aktif_dosya', sa.String(length=512), nullable=True),
    sa.Column('mesaj_sayisi', sa.Integer(), nullable=False),
    sa.Column('toplam_token', sa.Integer(), nullable=False),
    sa.Column('toplam_maliyet_usd', sa.Float(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.Column('guncelleme_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_kimlik'], ['kullanicilar.kimlik'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('sohbet_oturumlari', schema=None) as batch_op:
        batch_op.create_index('ix_sohbet_oturumlari_guncelleme_tarihi', ['guncelleme_tarihi'], unique=False)
        batch_op.create_index('ix_sohbet_oturumlari_kullanici_kimlik', ['kullanici_kimlik'], unique=False)

    op.create_table('api_cagrilari',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('oturum_kimlik', sa.String(length=36), nullable=True),
    sa.Column('kullanici_kimlik', sa.String(length=36), nullable=True),
    sa.Column('tedarikci', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('durum', sa.String(length=16), nullable=False),
    sa.Column('hata_kodu', sa.String(length=32), nullable=True),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.Column('istek_token', sa.Integer(), nullable=True),
    sa.Column('yanit_token', sa.Integer(), nullable=True),
    sa.Column('toplam_token', sa.Integer(), nullable=True),
    sa.Column('maliyet_usd', sa.Float(), nullable=True),
    sa.Column('sure_ms', sa.Integer(), nullable=True),
    sa.Column('ip_adresi', sa.String(length=64), nullable=True),
    sa.Column('mac_adresi', sa.String(length=32), nullable=True),
    sa.Column('istek_onizleme', sa.Text(), nullable=True),
    sa.Column('yanit_onizleme', sa.Text(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_kimlik'], ['kullanicilar.kimlik'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oturum_kimlik'], ['sohbet_oturumlari.kimlik'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('api_cagrilari', schema=None) as batch_op:
        batch_op.create_index('ix_api_cagrilari_durum', ['durum'], unique=False)
        batch_op.create_index('ix_api_cagrilari_kullanici_kimlik', ['kullanici_kimlik'], unique=False)
        batch_op.create_index('ix_api_cagrilari_model', ['model'], unique=False)
        batch_op.create_index('ix_api_cagrilari_olusturulma_tarihi', ['olusturulma_tarihi'], unique=False)
        batch_op.create_index('ix_api_cagrilari_oturum_kimlik', ['oturum_kimlik'], unique=False)
        batch_op.create_index('ix_api_cagrilari_tedarikci', ['tedarikci'], unique=False)

    op.create_table('sohbet_mesajlari',
    sa.Column('kimlik', sa.String(length=36), nullable=False),
    sa.Column('oturum_kimlik', sa.String(length=36), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('istek_token', sa.Integer(), nullable=True),
    sa.Column('yanit_token', sa.Integer(), nullable=True),
    sa.Column('toplam_token', sa.Integer(), nullable=True),
    sa.Column('maliyet_usd', sa.Float(), nullable=True),
    sa.Column('sure_ms', sa.Integer(), nullable=True),
    sa.Column('rag_kaynaklar', sa.JSON(), nullable=True),
    sa.Column('ui_aksiyonu', sa.JSON(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['oturum_kimlik'], ['sohbet_oturumlari.kimlik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('sohbet_mesajlari', schema=None) as batch_op:
        batch_op.create_index('ix_sohbet_mesajlari_oturum_kimlik', ['oturum_kimlik'], unique=False)
        batch_op.create_index('ix_sohbet_mesajlari_rol', ['rol'], unique=False)

    op.create_table('vektor_parcalari',
    sa.Column('kimlik', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('belge_kimlik', sa.String(length=36), nullable=False),
    sa.Column('chromadb_kimlik', sa.String(length=128), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('konum_imi', sa.String(length=256), nullable=True),
    sa.Column('sayfa_no', sa.Integer(), nullable=True),
    sa.Column('sinir_kutusu', sa.String(length=256), nullable=True),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['belge_kimlik'], ['belgeler.kimlik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kimlik'),
    sa.UniqueConstraint('chromadb_kimlik')
    )
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.create_index('ix_vektor_parcalari_belge_kimlik', ['belge_kimlik'], unique=False)
        batch_op.create_index('ix_vektor_parcalari_chromadb_kimlik', ['chromadb_kimlik'], unique=False)
        batch_op.create_index('ix_vektor_parcalari_sayfa_no', ['sayfa_no'], unique=False)

    op.create_table('bilgi_iliskileri',
    sa.Column('kimlik', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kaynak_parca_kimlik', sa.Integer(), nullable=False),
    sa.Column('hedef_parca_kimlik', sa.Integer(), nullable=False),
    sa.Column('iliski_turu', sa.String(length=64), nullable=False),
    sa.Column('agirlik', sa.Float(), nullable=True),
    sa.Column('kaynak', sa.String(length=16), nullable=False),
    sa.Column('olusturulma_tarihi', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hedef_parca_kimlik'], ['vektor_parcalari.kimlik'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kaynak_parca_kimlik'], ['vektor_parcalari.kimlik'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kimlik')
    )
    with op.batch_alter_table('bilgi_iliskileri', schema=None) as batch_op:
        batch_op.create_index('ix_bilgi_iliskileri_hedef', ['hedef_parca_kimlik'], unique=False)
        batch_op.create_index('ix_bilgi_iliskileri_kaynak', ['kaynak_parca_kimlik'], unique=False)
        batch_op.create_index('ix_bilgi_iliskileri_turu', ['iliski_turu'], unique=False)

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relations_source'))
        batch_op.drop_index(batch_op.f('ix_relations_target'))
        batch_op.drop_index(batch_op.f('ix_relations_type'))

    op.drop_table('relations')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_logs_model'))
        batch_op.drop_index(batch_op.f('ix_api_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_api_logs_user_id'))

    op.drop_table('api_logs')
    op.drop_table('user_models')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_chroma_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_chroma_id'))
        batch_op.drop_index(batch_op.f('ix_nodes_document_id'))

    op.drop_table('nodes')
    op.drop_table('user_roles')
    with op.batch_alter_table('knowledge_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_from_chunk'))
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_from_doc'))
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_relation'))

    op.drop_table('knowledge_edges')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_access_role'))
        batch_op.drop_index(batch_op.f('ix_documents_chroma_collection'))
        batch_op.drop_index(batch_op.f('ix_documents_file_type'))

    op.drop_table('documents')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))

    op.drop_table('chat_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=128), nullable=True),
    sa.Column('message_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_updated_at'), ['updated_at'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('uploader_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=512), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('chroma_collection', sa.VARCHAR(length=128), nullable=True),
    sa.Column('chunk_count', sa.INTEGER(), nullable=False),
    sa.Column('access_role', sa.VARCHAR(length=64), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('is_vectorized', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_chroma_collection'), ['chroma_collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_access_role'), ['access_role'], unique=False)

    op.create_table('knowledge_edges',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('from_doc_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('from_chunk_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('to_doc_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('to_chunk_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('relation', sa.VARCHAR(length=64), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_edges_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_edges_from_doc'), ['from_doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_edges_from_chunk'), ['from_chunk_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('assigned_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chroma_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('location_marker', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_chroma_id'), ['chroma_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.Column('last_login_at', sa.VARCHAR(length=32), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('chroma_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('bbox', sa.VARCHAR(length=128), nullable=True),
    sa.Column('text_preview', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_chroma_id'), ['chroma_id'], unique=False)

    op.create_table('user_models',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=512), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_user_models_name'))
    )
    op.create_table('api_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=16), nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True),
    sa.Column('cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('mac', sa.VARCHAR(length=32), nullable=True),
    sa.Column('request_preview', sa.TEXT(), nullable=True),
    sa.Column('response_preview', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_logs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_logs_created_at'), ['created_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True),
    sa.Column('cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('rag_sources', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_node_id', sa.INTEGER(), nullable=False),
    sa.Column('target_node_id', sa.INTEGER(), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relations_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_target'), ['target_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_source'), ['source_node_id'], unique=False)

    with op.batch_alter_table('bilgi_iliskileri', schema=None) as batch_op:
        batch_op.drop_index('ix_bilgi_iliskileri_turu')
        batch_op.drop_index('ix_bilgi_iliskileri_kaynak')
        batch_op.drop_index('ix_bilgi_iliskileri_hedef')

    op.drop_table('bilgi_iliskileri')
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.drop_index('ix_vektor_parcalari_sayfa_no')
        batch_op.drop_index('ix_vektor_parcalari_chromadb_kimlik')
        batch_op.drop_index('ix_vektor_parcalari_belge_kimlik')

    op.drop_table('vektor_parcalari')
    with op.batch_alter_table('sohbet_mesajlari', schema=None) as batch_op:
        batch_op.drop_index('ix_sohbet_mesajlari_rol')
        batch_op.drop_index('ix_sohbet_mesajlari_oturum_kimlik')

    op.drop_table('sohbet_mesajlari')
    with op.batch_alter_table('api_cagrilari', schema=None) as batch_op:
        batch_op.drop_index('ix_api_cagrilari_tedarikci')
        batch_op.drop_index('ix_api_cagrilari_oturum_kimlik')
        batch_op.drop_index('ix_api_cagrilari_olusturulma_tarihi')
        batch_op.drop_index('ix_api_cagrilari_model')
        batch_op.drop_index('ix_api_cagrilari_kullanici_kimlik')
        batch_op.drop_index('ix_api_cagrilari_durum')

    op.drop_table('api_cagrilari')
    with op.batch_alter_table('sohbet_oturumlari', schema=None) as batch_op:
        batch_op.drop_index('ix_sohbet_oturumlari_kullanici_kimlik')
        batch_op.drop_index('ix_sohbet_oturumlari_guncelleme_tarihi')

    op.drop_table('sohbet_oturumlari')
    op.drop_table('kullanici_roller')
    with op.batch_alter_table('denetim_izleri', schema=None) as batch_op:
        batch_op.drop_index('ix_denetim_izleri_tablo_adi')
        batch_op.drop_index('ix_denetim_izleri_olusturulma_tarihi')
        batch_op.drop_index('ix_denetim_izleri_kullanici_kimlik')
        batch_op.drop_index('ix_denetim_izleri_islem_turu')

    op.drop_table('denetim_izleri')
    with op.batch_alter_table('bilgisayar_oturumlari', schema=None) as batch_op:
        batch_op.drop_index('ix_bilgisayar_oturumlari_son_aktivite')
        batch_op.drop_index('ix_bilgisayar_oturumlari_mac_adresi')
        batch_op.drop_index('ix_bilgisayar_oturumlari_ip_adresi')

    op.drop_table('bilgisayar_oturumlari')
    with op.batch_alter_table('belgeler', schema=None) as batch_op:
        batch_op.drop_index('ix_belgeler_yukleyen_kimlik')
        batch_op.drop_index('ix_belgeler_vektordb_koleksiyon')
        batch_op.drop_index('ix_belgeler_erisim_politikasi')
        batch_op.drop_index('ix_belgeler_durum')
        batch_op.drop_index('ix_belgeler_dosya_turu')

    op.drop_table('belgeler')
    with op.batch_alter_table('sistem_ayarlari', schema=None) as batch_op:
        batch_op.drop_index('ix_sistem_ayarlari_anahtar')

    op.drop_table('sistem_ayarlari')
    op.drop_table('roller')
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.drop_index('ix_kullanicilar_eposta')

    op.drop_table('kullanicilar')
    with op.batch_alter_table('ai_modelleri', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_modelleri_tedarikci')

    op.drop_table('ai_modelleri')
    # ### end Alembic commands ###
