"""Add education models

Revision ID: ce6695cfbcfc
Revises: b3d9f4a20c58
Create Date: 2026-04-20 14:01:50.193319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce6695cfbcfc'
down_revision: Union[str, Sequence[str], None] = 'b3d9f4a20c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.alter_column('meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_vektor_parcalari_arama_vektoru'), postgresql_using='gin')
        batch_op.drop_column('arama_vektoru')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vektor_parcalari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arama_vektoru', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_vektor_parcalari_arama_vektoru'), ['arama_vektoru'], unique=False, postgresql_using='gin')
        batch_op.alter_column('meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
