"""add_allowed_workflows_to_ai_agents

Revision ID: ea59fb26e0da
Revises: 58a58a9a5859
Create Date: 2026-04-28 08:36:16.318056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea59fb26e0da'
down_revision: Union[str, Sequence[str], None] = '58a58a9a5859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_workflows', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_agents', schema=None) as batch_op:
        batch_op.drop_column('allowed_workflows')

    # ### end Alembic commands ###
